### ISSUE TITLE
【请教】增加其他高亮或文字颜色

### ISSUE THREAD

**Issue by mtuwei** [sethyuan/logseq-plugin-wrap#10]
开发者，您好！

首先感谢开发了这款实用插件，和音视频时间戳一样棒！有一个小问题不知可否请教您：

- 如何能够给文字增加其他颜色，例如：黄色。看了您的说明文档，感觉应该是可以的。具体操作的时候遇到了些小问题：

```
"wrap-yellow-text": {
    "label": "Wrap with yellow text",
    "binding": "",
    "template": "[[$yellow]]==$^==",
    "icon": "<svg t=\"1643270432116\" class=\"icon\" viewBox=\"0 0 1024 1024\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" p-id=\"12761\" width=\"200\" height=\"200\"><path d=\"M256 768h512a85.333333 85.333333 0 0 1 85.333333 85.333333v42.666667a85.333333 85.333333 0 0 1-85.333333 85.333333H256a85.333333 85.333333 0 0 1-85.333333-85.333333v-42.666667a85.333333 85.333333 0 0 1 85.333333-85.333333z m0 85.333333v42.666667h512v-42.666667H256z m401.578667-341.333333H366.421333L298.666667 682.666667H213.333333l256.128-640H554.666667l256 640h-85.333334l-67.754666-170.666667z m-33.877334-85.333333L512 145.365333 400.298667 426.666667h223.402666z\" p-id=\"12762\" fill=\"#FFFF00\"></path></svg>"
  },
```
上面这段代码添加后，能够在工具栏显示出来。由于【内置高亮与文字色】没有黄色，所以想请问下面这段代码我应该添加到哪个地方

```
span[data-ref="$yellow"] + mark {
  color: #ffff00;
  background: unset;
  padding: 0;
  border-radius: 0;
}
```

谢谢解答！

**Comment by sethyuan** [comment]
添加到你的`custom.css`文件中，可以通过下面这里访问：

![image](https://user-images.githubusercontent.com/3410293/159383928-7eeb69cf-002e-4d5d-8576-21b569f0aac1.png)

另外你的CSS应该是这样：

```css
span[data-ref="$yellow"] {
  display: none;
}
span[data-ref="$yellow"] + mark {
  color: #ffff00;
  background: unset;
  padding: 0;
  border-radius: 0;
}
```
