### ISSUE TITLE
Can you add Kindle highlight colors as a option?

### ISSUE THREAD

**Issue by Pvazevedo** [sethyuan/logseq-plugin-wrap#15]
Could you make a code block available in the readme for those who want to implement the Kindle highlights color palette in the plugin?
I tried to change the colors but I didn't succeed, I was only able to change the icon color and their order, not the highlights color itself.

Thx, for the plugin!

**Comment by sethyuan** [comment]
The code for customizing the highlight colors is in the bottom part of the README.

![image](https://user-images.githubusercontent.com/3410293/168454579-94e5bbee-525a-4520-91d3-2ae8002b78cc.png)

**Comment by Pvazevedo** [comment]
Do I put this code in the settings file or in the custom.css? It wasn't clear when I read the readme file.

**Comment by sethyuan** [comment]
You need to add `#brown` in here too:

```css
span[data-ref="#red"],
span[data-ref="#green"],
span[data-ref="#blue"],
span[data-ref="#brown"],
span[data-ref="$red"],
span[data-ref="$green"],
span[data-ref="$blue"] {
  display: none;
}
```
