### ISSUE TITLE
Unable to modify styles of wraps

### ISSUE THREAD

**Issue by gmalone** [sethyuan/logseq-plugin-wrap#31]
Hello @sethyuan, 

I've tried modifying the styles of the various color wrappings, but I seem unable to effect any changes. 

I was wondering if the plugin is somehow _overriding_ any attempts at CSS mods?

In custom.css, I've added your style code for the plugin.

Below example of what does _not_ work.
I've set the color for the RED wrapping to be BLUE.  It doesn't work.

<code>span[data-ref="$red"]  {
  color: #00f !important;
  background: unset !important;
  padding: 0;
  border-radius: 0;
  text-decoration: none !important;
}</code>

Can you advise me?  Thank you!

**Comment by sethyuan** [comment]
The CSS selector you applied is wrong, you can refer to the README' section regarding style customization.

```css
span[data-ref="$red"] + mark {
  color: #f00 !important;
  background: unset !important;
  padding: 0;
  border-radius: 0;
}
```
