### ISSUE TITLE
FR: Adapt the highlight and text colours based on light and dark modes

### ISSUE THREAD

**Issue by AvijeetPrasad** [sethyuan/logseq-plugin-wrap#35]
Hi,

It would be really useful if we could define separate colour schemes for light and dark modes. Currently if we optimise the colours for one mode (say light), it really stands out in the other!

**Comment by sethyuan** [comment]
A custom css can do the trick.

```css
html.dark #kef-wrap-toolbar {
  background: #...;
}
```
