### ISSUE TITLE
Interferes with theme colors

### ISSUE THREAD

**Issue by c6p** [sethyuan/logseq-plugin-wrap#5]
Hi @sethyuan
Thank you for the plugin.

I'm using bonofix dark theme, though there may be clashes with other themes too. Since bonofix specifies CSS rules more precisely than the plugin, plugin-wrap fails to change the colors.
```css
.dark-theme .content mark {
    color: var(--ls-primary-text-color);
    background: rgb(89, 86, 59);
}
```

Is there any way to set CSS for `mark` element without building myself? I guess there is no option for custom CSS in the settings. It may come handy when one wants to change the colors too.

As a workaround, what do you think about adding `!important` to `color` and `background` to override theme defaults.
